name: Build and deploy Node.js app to Azure Web App - qr-code-generator-romain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x 'node_modules/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip files
        run: unzip release.zip -d ./deployment

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0045F62E6D9E48E880049E01A923ACAB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03BA51B6D378478AB736296EB5AF83F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D990B20C971246008DAF78744FB3673F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'qr-code-generator-romain'
          slot-name: 'Production'
          package: ./deployment
          restart: true  # Critical for Node.js apps
          start-up-command: "npm start"  # Explicit start command
